# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9c494b6f9f7049a03321d29a3a8f2879dc442572cf2ed9c7abd3a238468a5b52ba7b1e73aef5721c52874e52701bb544b722930ef289504e70a217007fc403

test:
  secret_key_base: 23731083b2602f5b082d197562e33b1e9bb48957cf7d78a0175e2215f112abaecf81bbffb0ba61a5ed84668a25445548f18ee91f26237ae1e638554fb6eb43da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
